export const getBalanceSheetHTML = (balanceData: {
  totalPurchase: number;
  totalSales: number;
  inventoryValue: number;
  profit: number;
}) => `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Balance Sheet</title>
<style>
  body { font-family: Arial, sans-serif; margin: 20px; color: #000; }
  h1 { text-align: center; margin-bottom: 5px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th, td { border: 1px solid #444; padding: 6px 8px; font-size: 12px; }
  th { background-color: #f2e6ff; text-align: center; }
  .section-title { font-weight: bold; background: #fce5cd; text-align: left; }
  .sub-section { font-weight: bold; background: #f9f9f9; }
  .right { text-align: right; }
</style>
</head>
<body>
<h1>BALANCE SHEET</h1>
<p><b>Balance Sheet as at:</b> ${new Date().toLocaleDateString()}</p>
<table>
<tr>
<th colspan="2">Particulars</th>
<th>Figures current</th>
<th colspan="2">Particulars</th>
<th>Figures current</th>
</tr>
<tr>
<td colspan="3" class="section-title">I. EQUITY AND LIABILITIES</td>
<td colspan="3" class="section-title">II. ASSETS</td>
</tr>
<tr>
<td colspan="3" class="sub-section">(1) Shareholder’s Funds</td>
<td colspan="3" class="sub-section">(1) Non-current Assets</td>
</tr>
<tr>
<td>(a) Share Capital</td><td></td><td class="right">₹${balanceData.totalPurchase}</td>
<td>(a) Fixed Assets</td><td>(i) Tangible Assets</td><td class="right">₹${balanceData.inventoryValue}</td>
</tr>
<tr>
<td>(b) Reserves & Surplus</td><td></td><td class="right">₹${balanceData.profit}</td>
<td></td><td>(ii) Intangible Assets</td><td></td>
</tr>
<tr>
<td colspan="3" class="sub-section">(2) Non-current Liabilities</td>
<td colspan="3" class="sub-section">(2) Current Assets</td>
</tr>
<tr>
<td>(a) Long-term borrowings</td><td></td><td></td>
<td>(a) Inventories</td><td></td><td class="right">₹${balanceData.inventoryValue}</td>
</tr>
<tr>
<td>(b) Deferred tax liabilities</td><td></td><td></td>
<td>(b) Cash & Bank</td><td></td><td class="right">₹${balanceData.totalSales}</td>
</tr>
<tr>
<td colspan="3" class="sub-section">(3) Current Liabilities</td><td></td><td></td><td></td>
</tr>
<tr>
<td>(a) Trade Payables</td><td></td><td class="right">₹${balanceData.totalPurchase}</td>
<td></td><td></td><td></td>
</tr>
<tr>
<td colspan="2"><b>Total Liabilities & Equity</b></td><td class="right"><b>₹${
  balanceData.totalPurchase + balanceData.profit
}</b></td>
<td colspan="2"><b>Total Assets</b></td><td class="right"><b>₹${
  balanceData.inventoryValue + balanceData.totalSales
}</b></td>
</tr>
</table>
<p style="text-align:center; font-size:12px; color:#555; margin-top:30px;">Generated by Hisab Kitab App</p>
</body>
</html>
`;
